### ISSUE TITLE
버그2

### ISSUE THREAD

**Issue by egoing** [egoingsb/connect-git-240828#9]

**Comment by rasauq1122** [comment]
여기다

**Comment by Dangtae** [comment]
가보자

**Comment by Dangtae** [comment]
19조 화이팅

**Comment by taeyoung1005** [comment]
CV 1조 화이팅

**Comment by boyamie** [comment]
21조화이팅

**Comment by egoing** [comment]
fixed

**Comment by egoing** [comment]
여러분 복습하고 계시죠? ㅎㅎ

**Comment by Dangtae** [comment]
코테 스터디 팀 레포 하나 파서 연습하고 있습니다!

**Comment by limhongcheol** [comment]
잘 기억이 안나요! 다시 수업 듣고싶어요!

**Comment by minrongtic** [comment]
> 코테 스터디 팀 레포 하나 파서 연습하고 있습니다!

방금까지 피어세션에서 코테 스터디랑 백준허브 커스터마이징해서 깃 관리하는 거 같이 공부했습니다! 🤗🫡

**Comment by Solsol1014** [comment]
이고잉님 짱짱... 헷갈렸던 개념들도 다시 잘 이해돼서 흡수시킨 느낌이었습니다 🥳🥳

**Comment by minrongtic** [comment]
Covid19조만의 이고잉님🤩

**Comment by egoing** [comment]
깃 강의 준비하다가 여러분 생각나서 오랜만에 인사드립니다. 모두 건강하시고 한해 잘 마무리하세요!
